apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-container
            image: app-image
            command: ["sh", "-c", "echo Hello, World!"]
          restartPolicy: OnFailure

