apiVersion: v1
kind: Pod
metadata:
  name: app-volumeMounts
spec:
  containers:
  - name: app
    image: myapp
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}

