apiVersion: v1
kind: Pod
metadata:
  name: app-readinessProbe
spec:
  containers:
  - name: app
    image: nginx
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1

