apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-multicontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-multicontainer
  template:
    metadata:
      labels:
        app: app-multicontainer
    spec:
      containers:
      - name: app
        image: my-app
        ports:
        - containerPort: 8080
      - name: sidecar
        image: my-sidecar
        ports:
        - containerPort: 9090
        env:
        - name: APP_URL
          value: http://app:8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-multicontainer
spec:
  selector:
    app: app-multicontainer
  ports:
  - name: app
    port: 80
    targetPort: 8080
  - name: sidecar
    port: 9090
    targetPort: 9090

