---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: demo
  labels: 
    app: demo
    run: demo
spec:
  containers:
    - image: gcr.io/my-k8s-k3s/demo:v2.0.0
      name: app
      ports:
        - containerPort: 8000
          name: http